In [1]:
import pandas as pd

In [2]:
x1 = pd.read_csv(r'D:/FYP dataset/ARP MitM/ARP_MitM_dataset.csv',header=None)
x1

,0,1,2,3,4,5,6,7,8,9,...,105,106,107,108,109,110,111,112,113,114
0,1.000000,1294.000000,0.000000e+00,1.000000,1294.000000,0.000000e+00,1.000000,1294.000000,0.000000e+00,1.000000,...,0.000000e+00,0.0,0.0,1.000000,1294.000000,0.000000,1294.000000,0.000000e+00,0.0,0.0
1,1.000000,1514.000000,0.000000e+00,1.000000,1514.000000,0.000000e+00,1.000000,1514.000000,0.000000e+00,1.000000,...,0.000000e+00,0.0,0.0,1.000000,1514.000000,0.000000,1514.000000,0.000000e+00,0.0,0.0
2,1.999505,1294.000000,6.984919e-10,1.999703,1294.000000,2.328306e-10,1.999901,1294.000000,6.984919e-10,1.999990,...,0.000000e+00,0.0,0.0,1.999999,1294.000000,0.000000,1294.000000,0.000000e+00,0.0,0.0
3,2.998985,1294.000000,9.313226e-10,2.999391,1294.000000,4.656613e-10,2.999797,1294.000000,6.984919e-10,2.999980,...,6.984919e-10,0.0,0.0,2.999998,1294.000000,0.000015,1294.000000,2.328306e-10,0.0,0.0
4,3.998061,1294.000000,9.313226e-10,3.998836,1294.000000,2.328306e-10,3.999612,1294.000000,6.984919e-10,3.999961,...,2.328306e-10,0.0,0.0,3.999996,1294.000000,0.000000,1294.000000,0.000000e+00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2504262,380.551133,1331.684771,1.895906e+05,650.148549,1336.357995,1.865743e+05,1973.033776,1339.428666,1.851917e+05,19664.853626,...,1.813631e+05,0.0,0.0,28040.717202,1341.152101,425.618618,1341.152101,1.811512e+05,0.0,0.0
2504263,379.629067,1332.165017,1.891785e+05,649.176314,1336.631637,1.863354e+05,1972.036680,1339.517190,1.851133e+05,19663.862251,...,1.813090e+05,0.0,0.0,28041.433233,1341.158265,425.612280,1341.158265,1.811458e+05,0.0,0.0
2504264,380.276647,1332.643182,1.887678e+05,649.814659,1336.904590,1.860970e+05,1972.670406,1339.605640,1.850348e+05,19664.496996,...,1.812549e+05,0.0,0.0,28042.381146,1341.164429,425.605943,1341.164429,1.811404e+05,0.0,0.0
2504265,379.354717,1333.121248,1.883566e+05,648.842152,1337.177530,1.858584e+05,1971.672375,1339.694090,1.849564e+05,19663.504357,...,1.812009e+05,0.0,0.0,28043.096975,1341.170592,425.599606,1341.170592,1.811350e+05,0.0,0.0
2504266,379.951197,1333.597306,1.879468e+05,649.427959,1337.449804,1.856203e+05,1972.252742,1339.782469,1.848780e+05,19664.085817,...,1.811468e+05,0.0,0.0,28044.037284,1341.176755,425.593269,1341.176755,1.811296e+05,0.0,0.0

In [3]:
y1 = pd.read_csv(r'D:/FYP dataset/ARP MitM/ARP_MitM_labels.csv')
y1

         Unnamed: 0  x
0                 1  0
1                 2  0
2                 3  0
3                 4  0
4                 5  0
...             ... ..
2504262     2504263  1
2504263     2504264  1
2504264     2504265  1
2504265     2504266  1
2504266     2504267  1

[2504267 rows x 2 columns]

In [4]:
x2 = pd.read_csv(r'D:/FYP dataset/SSDP Flood/SSDP_Flood_dataset.csv',header=None)
x2

,0,1,2,3,4,5,6,7,8,9,...,105,106,107,108,109,110,111,112,113,114
0,1.000000,209.000000,0.000000e+00,1.000000,209.000000,0.000000e+00,1.000000,209.000000,0.000000e+00,1.000000,...,0.000000e+00,0.0,0.0,1.000000,209.000000,0.000000,209.000000,0.000000e+00,0.0,0.0
1,1.997162,830.381872,3.850195e+05,1.998296,830.029123,3.850200e+05,1.999432,829.676374,3.850202e+05,1.999943,...,0.000000e+00,0.0,0.0,1.000000,1450.000000,0.000000,1450.000000,0.000000e+00,0.0,0.0
2,2.996940,586.005354,3.758057e+05,2.998163,585.869927,3.757193e+05,2.999387,585.734436,3.756328e+05,2.999939,...,3.080250e+03,0.0,0.0,1.999994,153.499836,55.500000,153.499836,3.080250e+03,0.0,0.0
3,3.994740,802.288440,4.218196e+05,3.996842,802.073133,4.217991e+05,3.998947,801.857734,4.217785e+05,3.999895,...,0.000000e+00,0.0,0.0,1.999998,1450.000000,0.000022,1450.000000,4.656613e-10,0.0,0.0
4,4.994129,661.265167,4.167900e+05,4.996476,661.159177,4.167368e+05,4.998825,661.053084,4.166835e+05,4.999882,...,2.737938e+03,0.0,0.0,2.999991,134.999832,52.325843,134.999832,2.737994e+03,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4077261,7430.838735,136.000000,3.637979e-11,12386.459998,136.000000,8.731149e-11,37157.800970,136.000000,1.928129e-10,354099.428872,...,7.275958e-12,0.0,0.0,22.486489,136.000000,0.000000,136.000000,0.000000e+00,0.0,0.0
4077262,7430.862528,136.000000,3.637979e-11,12386.483629,136.000000,8.731149e-11,37157.824617,136.000000,1.928129e-10,354099.498434,...,0.000000e+00,0.0,0.0,26.717578,136.000000,0.000000,136.000000,0.000000e+00,0.0,0.0
4077263,7430.984547,136.000000,3.637979e-11,12386.605506,136.000000,8.731149e-11,37157.946511,136.000000,2.037268e-10,354099.661625,...,3.637979e-12,0.0,0.0,16.136518,136.000000,0.000003,136.000000,1.091394e-11,0.0,0.0
4077264,7430.105886,136.000000,3.637979e-11,12385.726502,136.000000,8.731149e-11,37157.067507,136.000000,2.000888e-10,354098.870972,...,0.000000e+00,0.0,0.0,12.443898,136.000000,0.000003,136.000000,7.275958e-12,0.0,0.0
4077265,7431.081328,136.000000,3.637979e-11,12386.701940,136.000000,8.731149e-11,37158.042945,136.000000,1.891749e-10,354099.847565,...,3.637979e-12,0.0,0.0,15.575927,136.000000,0.000003,136.000000,7.275958e-12,0.0,0.0

In [5]:
y2 = pd.read_csv(r'D:/FYP dataset/SSDP Flood/SSDP_Flood_labels.csv')
y2

         Unnamed: 0  x
0                 1  0
1                 2  0
2                 3  0
3                 4  0
4                 5  0
...             ... ..
4077261     4077262  1
4077262     4077263  1
4077263     4077264  1
4077264     4077265  1
4077265     4077266  1

[4077266 rows x 2 columns]

In [6]:
x = pd.concat([x1,x2])
x

,0,1,2,3,4,5,6,7,8,9,...,105,106,107,108,109,110,111,112,113,114
0,1.000000,1294.0,0.000000e+00,1.000000,1294.0,0.000000e+00,1.000000,1294.0,0.000000e+00,1.000000,...,0.000000e+00,0.0,0.0,1.000000,1294.0,0.000000,1294.0,0.000000e+00,0.0,0.0
1,1.000000,1514.0,0.000000e+00,1.000000,1514.0,0.000000e+00,1.000000,1514.0,0.000000e+00,1.000000,...,0.000000e+00,0.0,0.0,1.000000,1514.0,0.000000,1514.0,0.000000e+00,0.0,0.0
2,1.999505,1294.0,6.984919e-10,1.999703,1294.0,2.328306e-10,1.999901,1294.0,6.984919e-10,1.999990,...,0.000000e+00,0.0,0.0,1.999999,1294.0,0.000000,1294.0,0.000000e+00,0.0,0.0
3,2.998985,1294.0,9.313226e-10,2.999391,1294.0,4.656613e-10,2.999797,1294.0,6.984919e-10,2.999980,...,6.984919e-10,0.0,0.0,2.999998,1294.0,0.000015,1294.0,2.328306e-10,0.0,0.0
4,3.998061,1294.0,9.313226e-10,3.998836,1294.0,2.328306e-10,3.999612,1294.0,6.984919e-10,3.999961,...,2.328306e-10,0.0,0.0,3.999996,1294.0,0.000000,1294.0,0.000000e+00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4077261,7430.838735,136.0,3.637979e-11,12386.459998,136.0,8.731149e-11,37157.800970,136.0,1.928129e-10,354099.428872,...,7.275958e-12,0.0,0.0,22.486489,136.0,0.000000,136.0,0.000000e+00,0.0,0.0
4077262,7430.862528,136.0,3.637979e-11,12386.483629,136.0,8.731149e-11,37157.824617,136.0,1.928129e-10,354099.498434,...,0.000000e+00,0.0,0.0,26.717578,136.0,0.000000,136.0,0.000000e+00,0.0,0.0
4077263,7430.984547,136.0,3.637979e-11,12386.605506,136.0,8.731149e-11,37157.946511,136.0,2.037268e-10,354099.661625,...,3.637979e-12,0.0,0.0,16.136518,136.0,0.000003,136.0,1.091394e-11,0.0,0.0
4077264,7430.105886,136.0,3.637979e-11,12385.726502,136.0,8.731149e-11,37157.067507,136.0,2.000888e-10,354098.870972,...,0.000000e+00,0.0,0.0,12.443898,136.0,0.000003,136.0,7.275958e-12,0.0,0.0
4077265,7431.081328,136.0,3.637979e-11,12386.701940,136.0,8.731149e-11,37158.042945,136.0,1.891749e-10,354099.847565,...,3.637979e-12,0.0,0.0,15.575927,136.0,0.000003,136.0,7.275958e-12,0.0,0.0

In [7]:
y = pd.concat([y1,y2])
y

         Unnamed: 0  x
0                 1  0
1                 2  0
2                 3  0
3                 4  0
4                 5  0
...             ... ..
4077261     4077262  1
4077262     4077263  1
4077263     4077264  1
4077264     4077265  1
4077265     4077266  1

[6581533 rows x 2 columns]

In [8]:
y.drop('Unnamed: 0', inplace=True, axis=1)
y

         x
0        0
1        0
2        0
3        0
4        0
...     ..
4077261  1
4077262  1
4077263  1
4077264  1
4077265  1

[6581533 rows x 1 columns]

In [10]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=2,init='k-means++',max_iter=10,n_init=4,random_state=4)
ykmeans=kmeans.fit_predict(x)

MemoryError: Unable to allocate 5.64 GiB for an array with shape (6581533, 115) and data type float64